project_id = "rodzscunpcafxjpmklhj"

[functions.remove-background]
verify_jwt = false

[functions.enhance-image]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.validate-session]
verify_jwt = false
